# Generated by Django 3.2.9 on 2021-12-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axie_market_scout_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='item',
            new_name='class_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
    ]
